trigger:
  branches:
    include:
    - refs/heads/master
    - refs/tags/*

jobs:
  - job: run_rustfmt
    displayName: "Run rust fmt"
    pool:
        vmImage: ubuntu-16.04
    steps:
    - template: ci/azure-install-rust.yml
    - script: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - script: |
        cargo fmt --all -- --check
      displayName: Check formatting

  - job: run_cargo_test
    displayName: "cargo test"
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)
    steps:
    - template: ci/azure-install-rust.yml
    - script: cargo test
      displayName: Cargo test

  - job: create_linux_binary
    displayName: "Create release binaries for Linux"
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml  
      - script: rustup target add x86_64-unknown-linux-musl
        displayName: Add unknown linux target
      - script: |
          sudo apt update -y
          sudo apt install musl-tools -y
        displayName: "Install musl-tools"
      - script: cargo build --target x86_64-unknown-linux-musl --features vendored-openssl --release
        displayName: cargo build
      - template: ci/azure-publish-artifact.yml
        parameters:
          artifacts: target/x86_64-unknown-linux-musl/release
          name: dist_linux        

  - job: create_windows_binary
    displayName: "Create release binaries for Windows"
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-install-rust.yml  
      - script: cargo build --release
        displayName: cargo build
      - template: ci/azure-publish-artifact.yml
        parameters:
          name: dist_windows                  

  - job: create_macOS_binary
    displayName: "Create release binaries for MacOS"
    pool:
      vmImage: macOS-10.13
    steps:
      - template: ci/azure-install-rust.yml  
      - script: cargo build --release
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.7        
        displayName: cargo build
      - template: ci/azure-publish-artifact.yml
        parameters:
          name: dist_macos 