[package]
name = "podium"
version = "0.0.1"
authors = ["Teodor Voinea <voinea.teodor@gmail.com>"]
edition = "2018"

[dependencies]
tantivy = "0.11.3"
walkdir = "2"
app_dirs = "^1.2.1"
notify = "4.0.0"
config = "0.10.1"
simple_logger = "1.5.0"
log = "0.4.6"
blake2b_simd = "0.5.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.4.0"
kamadak-exif = "0.3"
reverse_geocoder = { git = "https://github.com/llambda/rrgeo"}
pdf-extract = "0.4.6"
regex = "1"
image = "0.21.2"
docx = "0.1.2"
msoffice_pptx = "0.2.1"
msoffice_shared = "0.1.1"
csv = "1"
calamine = "0.15.4"
opener = "0.4.0"
# Windows support isn't great for tensorflow-rust yet tensorflow = "0.13.0"

[target."cfg(not(windows))".dependencies]
tract-tensorflow = "0.3.3"
tract-core = "0.3.3"

[dev-dependencies]
criterion = "0.2"

[lib]
name = "podium_lib"
path = "src/lib.rs"
bench = false

[[bin]]
name = "podium"
path = "src/bin.rs"
bench = false

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
overflow-checks = false

# [profile.bench]
# opt-level = 3
# debug = false
# rpath = false
# lto = false
# debug-assertions = false
# codegen-units = 16
# panic = 'unwind'
# incremental = false
# overflow-checks = false
